### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by tiagomarin** [amare1990/Recipe#13]
We are only 2 in the group!

link:
[Kanban Board](https://github.com/amare1990/Recipe/projects/1)

**Comment by OLIPLICHE** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Create Kanban board 👍 

## Required Changes ♻️
- Hi, I noticed that you are 2 in the group. I would advise you to focus on tasks provided for a team of 2 Members. you will be free to add what you want when your project will be approved. Therefore remove part 3 from your Kanban to avoid confusion. 

![Capture](https://user-images.githubusercontent.com/63972670/218494155-295435aa-cab7-4af1-a586-2c89ed9dd40a.PNG)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by omar-muhamad** [comment]
# Approved ✔
### Hi @,

Great job, Your project is complete!  There is nothing else to say other than... it's time close this issue and start working on the project :shipit: 

GOOD LUCK 🤞

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by medaminedev66** [comment]
Hello team 👋,

_This is an additional review as a result of the second opinion request._

Your CRR appears to have already received approval. Wishing you success on your capstone project  💯 .

Keep rocking 🚀!

**Comment by tiagomarin** [comment]
Thanks for answering to our request @medaminedev66 

happy coding 🥳
